### ISSUE TITLE
Unicode Behavior with Python 3

### ISSUE THREAD

**Issue by jjangsangy** [qadium/credstmpl#1]
Currently trying to render non-ascii characters using `credstmpl` gives this error.

[Taken from Travis-CI output](https://travis-ci.org/qadium-memex/linkalytics/jobs/91202856#L428)

```
$ credstmpl linkalytics/environment/common.cfg.j2
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.4.2/bin/credstmpl", line 9, in <module>
    load_entry_point('credstmpl==0.1.0', 'console_scripts', 'credstmpl')()
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/credstmpl/__init__.py", line 28, in main
    rendered_templates, skipped_templates = template.render(set(args.templates))
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/credstmpl/template.py", line 112, in render
    render_template(template, contents.dst)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/credstmpl/template.py", line 84, in render_template
    f.write(result)
TypeError: 'str' does not support the buffer interface
```

For better Python 2 & 3 behavior it might be possible to enforce unicode encoding explicitly through the `Environment` object in jinja2.

http://stackoverflow.com/questions/22181944/using-utf-8-characters-in-a-jinja2-template

**Comment by jjangsangy** [comment]
Commit 66aba73bb02049a1272e8e16906fc433fbd4f10e fixes issue, please close @echu

**Comment by echu** [comment]
LGTM. We had a conversation about this in person on 11/16. @jjangsangy made the requisite changes and properly tagged the new version.
